# Generated by Django 3.2 on 2022-09-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='address',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='address',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
    ]
