# Generated by Django 3.2 on 2022-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220901_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='key',
            new_name='staff_data',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='key',
            new_name='student_data',
        ),
    ]
