# Generated by Django 3.2 on 2022-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
